import { useState, useEffect, useCallback } from "react";

function App() {
  const [formData, setFormData] = useState({
    appName: "", email: "", description: "",
    collectsEmail: false, collectsLocation: false, usesCookies: false, isEU: false,
  });
  
  const [output, setOutput] = useState("");
  const [isViewMode, setIsViewMode] = useState(false);
  const [isPro, setIsPro] = useState(false);
  const [isValidating, setIsValidating] = useState(false);

  const generateText = useCallback((data, proStatus) => {
    const date = new Date().toLocaleDateString();

    // 1. THE "NOT A LAW FIRM" SHIELD
    const disclaimer = `*** IMPORTANT: This document is a computer-generated template and does not constitute legal advice. Legal Gen is not a law firm. You are solely responsible for reviewing, modifying, and ensuring the accuracy of all generated documents before use. ***\n\n`;

    let policy = `PRIVACY POLICY\nLast Updated: ${date}\n\n1. INTRODUCTION\nWelcome to ${data.appName || "our app"}. We respect your privacy.\n\n`;
    
    policy += `2. DATA WE COLLECT\n`;
    if (data.collectsEmail) policy += `- Email Address: May be used for account creation, communication, or support depending on app functionality.\n`;
    if (data.collectsLocation) policy += `- Location Data: May be used to provide location-based services or improve user experience.\n`;
    if (data.usesCookies) policy += `- Cookies & Analytics: We may use third-party tools to monitor app usage and improve performance.\n`;
    
    if (proStatus && data.isEU) {
      policy += `\n3. GDPR INFORMATION (EU USERS)\nIf you are located in the European Economic Area, you may have certain data protection rights under applicable laws. Under the GDPR, you have the right to access, rectify, or erase your data. Contact us at ${data.email || "[Support Email]"} to exercise these rights.\n`;
    }

    policy += `\n4. CONTACT\nQuestions? Contact us at: ${data.email || "[Support Email]"}\n`;

    // 2. THE "LIABILITY & REVOCATION" SHIELD 
    const terms = `TERMS OF SERVICE\n\n1. AGREEMENT\nBy using ${data.appName}, you agree to these terms.\n\n2. LIMITATION OF LIABILITY & LICENSE\nAccess to premium features is provided under a limited, non-transferable license and may be revoked if misuse or abuse is detected. This tool is provided "AS IS." To the maximum extent permitted by law, Legal Gen shall not be liable for any damages, legal issues, or App Store rejections arising from the use of generated documents. Use of this template does not guarantee compliance with privacy laws. You are solely responsible for ensuring the accuracy of all generated documents before use.`;
    
    const branding = proStatus ? "" : `\n\n------------------------------\nGenerated by Legal Gen (Free Version)`;
    setOutput(disclaimer + policy + "\n\n" + "=".repeat(30) + "\n\n" + terms + branding);
  }, []);

  const verifyLicense = useCallback(async (key) => {
    if (!key) return false;
    setIsValidating(true);
    try {
      const response = await fetch("/.netlify/functions/validate-license", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ license_key: key })
      });
      const result = await response.json();
      if (result.success) {
        setIsPro(true);
        localStorage.setItem("legalGen_Pro_Key", key);
        generateText(formData, true);
        return true;
      }
      localStorage.removeItem("legalGen_Pro_Key");
      setIsPro(false);
      return false;
    } catch (err) {
      console.error("License verification failed");
      return false;
    } finally {
      setIsValidating(false);
    }
  }, []);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const urlKey = params.get("license");
    const savedKey = localStorage.getItem("legalGen_Pro_Key");

    const init = async () => {
      let activePro = false;
      
      // Verification logic (Priority: URL > LocalStorage)
      if (urlKey) {
        activePro = await verifyLicense(urlKey);
        // UI Enhancement: Cleanup URL after success
        if (activePro) {
          window.history.replaceState({}, document.title, window.location.pathname);
        }
      } else if (savedKey) {
        // IMPROVEMENT: Re-verify saved keys silently
        activePro = await verifyLicense(savedKey);
      }

      // Secure Link Processing
      const encodedData = params.get("p");
      if (encodedData && encodedData.length < 2500) {
        try {
          const decoded = JSON.parse(atob(encodedData));
          const validKeys = ['appName', 'email', 'description', 'collectsEmail', 'collectsLocation', 'usesCookies', 'isEU'];
          const sanitized = {};
          validKeys.forEach(key => {
            if (Object.prototype.hasOwnProperty.call(decoded, key)) {
              sanitized[key] = typeof decoded[key] === 'boolean' ? decoded[key] : String(decoded[key]).substring(0, 500);
            }
          });
          if (sanitized.appName) {
            setFormData(prev => ({ ...prev, ...sanitized }));
            setIsViewMode(true);
            generateText(sanitized, activePro);
          }
        } catch (e) { console.error("Invalid share link"); }
      }
    };
    init();
  }, [generateText, verifyLicense]);

  const handleInput = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({ ...prev, [name]: type === "checkbox" ? checked : value }));
  };

  const downloadPDF = () => {
    if (!isPro) {
      alert("⚠️ PDF Export is a Pro feature.");
      return;
    }
    const element = document.getElementById('policy-content');
    const opt = {
      margin: 1,
      filename: `${formData.appName || 'App'}-Privacy-Policy.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };
    window.html2pdf().from(element).set(opt).save();
  };

  const handleGenerate = () => generateText(formData, isPro);

  const copyLink = () => {
    const encoded = btoa(JSON.stringify(formData));
    const link = `${window.location.origin}${window.location.pathname}?p=${encoded}`;
    navigator.clipboard.writeText(link);
    alert("Public link copied!");
  };

  if (isViewMode) {
    return (
      <div style={{ maxWidth: "800px", margin: "auto", padding: "40px", fontFamily: "serif", color: "#333" }}>
        <pre id="policy-content" style={{ whiteSpace: "pre-wrap", wordBreak: "break-word" }}>{output}</pre>
        <hr />
        <button onClick={() => window.location.href = window.location.origin} style={{ padding: "10px 20px", cursor: "pointer" }}>Create Your Own Policy</button>
      </div>
    );
  }

  return (
    <div style={{ maxWidth: "600px", margin: "auto", padding: "20px", fontFamily: "sans-serif" }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h1>Legal Gen ⚖️</h1>
        {isPro && <span style={{ background: '#ffd700', padding: '5px 10px', borderRadius: '15px', fontSize: '0.7rem', fontWeight: 'bold' }}>PRO</span>}
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
        <input name="appName" placeholder="App Name" value={formData.appName} onChange={handleInput} style={{padding: '8px'}} />
        <input name="email" placeholder="Support Email" value={formData.email} onChange={handleInput} style={{padding: '8px'}} />
        <textarea name="description" placeholder="Short description" value={formData.description} onChange={handleInput} style={{padding: '8px', height: '60px'}} />
        
        <div style={{ background: "#f4f4f4", padding: "15px", borderRadius: "8px" }}>
          <p style={{margin: 0, paddingBottom: "5px"}}><strong>Data Practices</strong></p>
          <label><input type="checkbox" name="collectsEmail" checked={formData.collectsEmail} onChange={handleInput} /> Email Addresses</label><br/>
          <label><input type="checkbox" name="collectsLocation" checked={formData.collectsLocation} onChange={handleInput} /> User Location</label><br/>
          <label><input type="checkbox" name="usesCookies" checked={formData.usesCookies} onChange={handleInput} /> Cookies/Analytics</label><br/>
          <label><input type="checkbox" name="isEU" checked={formData.isEU} onChange={handleInput} /> Include GDPR Clauses {!isPro && "🔒"}</label>
        </div>

        {!isPro && (
          <div style={{ background: '#fffcf0', border: '1px solid #ffd700', padding: '15px', borderRadius: '8px', textAlign: 'center' }}>
            <p style={{ margin: 0, fontSize: '0.9rem' }}><strong>{isValidating ? "Verifying License..." : "Unlock Pro - $9"}</strong></p>
            <button 
              disabled={isValidating} 
              onClick={() => window.open('https://indie-legalgen.lemonsqueezy.com/checkout/buy/b50e47cc-5d30-4532-b735-a408428fca3d', '_blank')} 
              style={{ background: '#000', color: '#fff', border: 'none', padding: '10px 20px', borderRadius: '5px', marginTop: '10px', cursor: 'pointer', fontWeight: 'bold', opacity: isValidating ? 0.5 : 1 }}
            >
              Get Pro Access
            </button>
          </div>
        )}

        <button onClick={handleGenerate} style={{ padding: "12px", background: "#007bff", color: "#fff", border: "none", borderRadius: "5px", cursor: 'pointer', fontWeight: 'bold' }}>
          Generate Documents
        </button>
      </div>

      {output && (
        <div style={{ marginTop: '20px' }}>
          <div style={{ marginBottom: '10px', display: 'flex', gap: '10px' }}>
            <button onClick={copyLink} style={{ background: '#6f42c1', color: '#fff', border: 'none', padding: '8px 12px', borderRadius: '4px', cursor: 'pointer' }}>Copy Hosted Link</button>
            <button 
              onClick={downloadPDF} 
              style={{ background: isPro ? '#28a745' : '#ccc', color: '#fff', border: 'none', padding: '8px 12px', borderRadius: '4px', cursor: isPro ? 'pointer' : 'not-allowed' }}
            >
              Download PDF {!isPro && "🔒"}
            </button>
          </div>
          <pre id="policy-content" style={{ whiteSpace: "pre-wrap", background: "#eee", padding: "20px", borderRadius: "5px", fontSize: "0.85rem", border: '1px solid #ddd' }}>{output}</pre>
        </div>
      )}
      
      <p style={{fontSize: '0.7rem', color: '#999', marginTop: '40px', textAlign: 'center'}}>
        Disclaimer: Legal Gen is not a law firm. Templates provided for educational purposes; user assumes all liability for final content.
      </p>
    </div>
  );
}

export default App;